apiVersion: v1
kind: Service
metadata:
  name: react-cicd-service
spec:
  type: NodePort 
  selector:
    app: react-cicd 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 30080