- name: Install K3s
  shell: "curl -sfL https://get.k3s.io | sh -"
  args:
    creates: /usr/local/bin/k3s

- name: Create K3s config directory if it does not exist
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"
  become: yes

- name: Configure K3s to trust the insecure Harbor registry
  ansible.builtin.template:
    src: registries.yml.j2
    dest: /etc/rancher/k3s/registries.yml
    mode: "0644"
  become: yes
  notify: "Restart K3s"