- name: Fix interrupted dpkg runs (if any)
  ansible.builtin.command: dpkg --configure -a
  become: yes
  changed_when: false

- name: Install Docker and Docker Compose
  apt:
    name: ['docker.io', 'docker-compose']
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes
